name: random_data
description: Generates random numbers, dates, strings, characters, names, durations, etc.
version: 1.5.2
homepage: https://github.com/cgrep-tool/random_data
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  string_unescape: ^1.5.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
