part of 'base.dart';

const _cities = [
  'Aba',
  'Abadan',
  'Abaetetuba',
  'Abakan',
  'Abbotabad',
  'Abbotsford',
  'Abengourou',
  'Abeokuta',
  'Aberdeen',
  'Abha',
  'Abidjan',
  'Baicheng',
  'Baidoa',
  'Baidyabati',
  'Baise',
  'Baishan',
  'Baiyin',
  'Cagua',
  'Caguas',
  'Cainta',
  'Cairns',
  'Cairo',
  'Cajamarca',
  'Danapur',
  'Dandong',
  'Dangyang',
  'Danjiangkou',
  'Danlí',
  'Danyang',
  'Daqing',
  'Emmen',
  'Engels',
  'English Bazar',
  'Enschede',
  'Ensenada',
  'Enshi',
  'Enugu',
  'Firozpur',
  'Flint',
  'Florence',
  'Florencia',
  'Florianópolis',
  'Floridablanca',
  'Foggia',
  'Fontana',
  'Forlì',
  'Formosa',
  'Nakhodka',
  'Nakhon Pathom',
  'Nakhon Ratchasima',
  'Nakhon Sawan',
  'Nakhon Si Thammarat',
  'Nakuru',
  'Nalchik',
  'Nalgonda',
  'Nam Định',
  'Ramadi',
  'Ramagundam',
  'Ramat Gan',
  'Rampur',
  'Ranaghat',
  'Rancagua',
  'Stavanger',
  'Stavropol',
  'Sterlitamak',
  'Stockholm',
  'Stockport',
  'Yaroslavl',
  'Yasuj',
  'Yatsushiro',
  'Yavatmal',
  'Yazd',
  'Yekaterinburg',
  'Zapopan',
  'Zaporizhia',
  'Zaragoza',
  'Zaria',
  'Zarqa',
  'Zelenograd',
];

const _citiesWithCountries = [
  'Aba,Nigeria',
  'Abadan,Iran',
  'Abaetetuba,Brazil',
  'Abakan,Russia',
  'Abbotabad,Pakistan',
  'Abbotsford,Canada',
  'Abengourou,Ivory Coast',
  'Abeokuta,Nigeria',
  'Aberdeen,United Kingdom',
  'Abha,Saudi Arabia',
  'Abidjan,Ivory Coast',
  'Baicheng,China',
  'Baidoa,Somalia',
  'Baidyabati,India',
  'Baise,China',
  'Baishan,China',
  'Baiyin,China',
  'Cagua,Venezuela',
  'Caguas,Puerto Rico',
  'Cainta,Philippines',
  'Cairns,Australia',
  'Cairo,Egypt',
  'Cajamarca,Peru',
  'Danapur,India',
  'Dandong,China',
  'Dangyang,China',
  'Danjiangkou,China',
  'Danlí,Honduras',
  'Danyang,China',
  'Daqing,China',
  'Emmen,Netherlands',
  'Engels,Russia',
  'English Bazar,India',
  'Enschede,Netherlands',
  'Ensenada,Mexico',
  'Enshi,China',
  'Enugu,Nigeria',
  'Firozpur,India',
  'Flint,United States',
  'Florence,Italy',
  'Florencia,Colombia',
  'Florianópolis,Brazil',
  'Floridablanca,Colombia',
  'Foggia,Italy',
  'Fontana,United States',
  'Forlì,Italy',
  'Formosa,Argentina',
  'Nakhodka,Russia',
  'Nakhon Pathom,Thailand',
  'Nakhon Ratchasima,Thailand',
  'Nakhon Sawan,Thailand',
  'Nakhon Si Thammarat,Thailand',
  'Nakuru,Kenya',
  'Nalchik,Russia',
  'Nalgonda,India',
  'Nam Định,Vietnam',
  'Ramadi,Iraq',
  'Ramagundam,India',
  'Ramat Gan,Israel',
  'Rampur,India',
  'Ranaghat,India',
  'Rancagua,Chile',
  'Stavanger,Norway',
  'Stavropol,Russia',
  'Sterlitamak,Russia',
  'Stockholm,Sweden',
  'Stockport,United Kingdom',
  'Yaroslavl,Russia',
  'Yasuj,Iran',
  'Yatsushiro,Japan',
  'Yavatmal,India',
  'Yazd,Iran',
  'Yekaterinburg,Russia',
  'Zapopan,Mexico',
  'Zaporizhia,Ukraine',
  'Zaragoza,Spain',
  'Zaria,Nigeria',
  'Zarqa,Jordan',
  'Zelenograd,Russia',
];
